###############################################
# Servo config for ur2 (dual-arm)
###############################################

override_velocity_scaling_factor: 1.0

publish_period: 0.01
low_latency_mode: false

command_in_type: speed_units
scale:
  linear:  0.4
  rotational:  0.8
  joint: 0.5

command_out_type: std_msgs/Float64MultiArray
publish_joint_positions: true
publish_joint_velocities: false
publish_joint_accelerations: false

use_smoothing: true
smoothing_filter_plugin_name: online_signal_smoothing::ButterworthFilterPlugin
butterworth_filter_order: 2
butterworth_low_pass_filter_coeff: 30.0

is_primary_planning_scene_monitor: false
check_octomap_collisions: false

move_group_name: ur_manipulator
planning_frame: ur2_base_link

ee_frame_name: tool0
robot_link_command_frame: ur2_base_link

incoming_command_timeout:  0.1
num_outgoing_halt_msgs_to_publish: 4

lower_singularity_threshold: 50.0
hard_stop_singularity_threshold: 100.0
leaving_singularity_threshold_multiplier: 2.0
joint_limit_margin: 0.1

cartesian_command_in_topic: ~/delta_twist_cmds
joint_command_in_topic: ~/delta_joint_cmds
joint_topic: /ur2/joint_states
status_topic: ~/status
command_out_topic: /ur2/forward_position_controller/commands

check_collisions: true
collision_check_rate: 10.0
collision_check_type: threshold_distance
self_collision_proximity_threshold: 0.01
scene_collision_proximity_threshold: 0.02
collision_distance_safety_factor: 10.0
min_allowable_collision_distance: 0.025
